#!/bin/sh

cd $1
md library
cd library

if [ ! -z "$IS_MINIMAL" ]; then
	remtrace Retrieve MINIMAL libraries
	remtrace base
	es_exprt /Src/$2/base base

	remtrace argument_parser
	es_exprt /Src/$2/argument_parser argument_parser
	remtrace base_extension
	es_exprt /Src/$2/base_extension base_extension
	remtrace diff
	es_exprt /Src/$2/diff diff
	remtrace process
	es_exprt /Src/$2/process process
	remtrace thread
	es_exprt /Src/$2/thread thread
	remtrace time
	es_exprt /Src/$2/time time
else
	remtrace Retrieve libraries
	remtrace api_wrapper
	es_exprt /Src/$2/api_wrapper api_wrapper
	remtrace argument_parser
	es_exprt /Src/$2/argument_parser argument_parser
	remtrace base
	es_exprt /Src/$2/base base
	remtrace base_extension
	es_exprt /Src/$2/base_extension base_extension
	remtrace cocoa
	es_exprt /Src/$2/cocoa cocoa
	remtrace cURL
	es_exprt /Src/$2/cURL cURL
	remtrace diff
	es_exprt /Src/$2/diff diff
	remtrace docking
	es_exprt /Src/$2/docking docking
	remtrace Eiffel2Java
	es_exprt /Src/$2/Eiffel2Java Eiffel2Java
	remtrace editor
	es_exprt /Src/$2/editor editor
	remtrace encoding
	es_exprt /Src/$2/encoding encoding
	remtrace event
	es_exprt /Src/$2/event event
	remtrace gobo
	es_exprt /Src/$2/gobo gobo
	fullrd gobo/svn/work
	remtrace gobo_extension
	es_exprt /Src/$2/gobo_extension gobo_extension
	remtrace graph
	es_exprt /Src/$2/graph graph
	remtrace i18n
	es_exprt /Src/$2/i18n i18n
	remtrace lex
	es_exprt /Src/$2/lex lex
	remtrace memory_analyzer
	es_exprt /Src/$2/memory_analyzer memory_analyzer
	remtrace net
	es_exprt /Src/$2/net net
	remtrace objc_base
	es_exprt /Src/$2/objc_base objc_base
	remtrace parse
	es_exprt /Src/$2/parse parse
	remtrace patterns
	es_exprt /Src/$2/patterns patterns
	remtrace preferences
	es_exprt /Src/$2/preferences preferences
	remtrace process
	es_exprt /Src/$2/process process
	remtrace runtime
	es_exprt /Src/$2/runtime runtime
	remtrace store
	es_exprt /Src/$2/store store
	remtrace testing
	es_exprt /Src/$2/testing testing
	remtrace text
	es_exprt /Src/$2/text text
	remtrace thread
	es_exprt /Src/$2/thread thread
	remtrace time
	es_exprt /Src/$2/time time
	remtrace uuid
	es_exprt /Src/$2/uuid uuid
	remtrace vision2
	es_exprt /Src/$2/vision2 vision2
	remtrace vision2_extension
	es_exprt /Src/$2/vision2_extension vision2_extension
	remtrace web
	es_exprt /Src/$2/web web
	remtrace web_browser
	es_exprt /Src/$2/web_browser web_browser
	remtrace wel
	es_exprt /Src/$2/wel wel
fi

