#!/bin/sh

remtrace Retrieve unstable libraries
cd $1
md unstable
cd unstable

remtrace README.txt
es_exprt /Src/unstable/README.txt README.txt

remtrace library
es_exprt /Src/unstable/library library


remtrace Retrieve contrib libraries and examples
cd $1
md contrib
cd contrib

remtrace README.txt
es_exprt /Src/contrib/README.txt README.txt

remtrace library
es_exprt /Src/contrib/library library

remtrace examples
es_exprt /Src/contrib/examples examples
