-- This file has been generated by EWG. Do not edit. Changes will be lost!

deferred class QDBITS_PROC_PTR_CALLBACK

feature {QDBITS_PROC_PTR_DISPATCHER}

	on_callback (a_srcbits: POINTER; a_srcrect: POINTER; a_dstrect: POINTER; a_mode: INTEGER; a_maskrgn: POINTER) is 
		deferred
		end

end
