-- This file has been generated by EWG. Do not edit. Changes will be lost!

deferred class QDCOMMENT_PROC_PTR_CALLBACK

feature {QDCOMMENT_PROC_PTR_DISPATCHER}

	on_callback (a_kind: INTEGER; a_datasize: INTEGER; a_datahandle: POINTER) is 
		deferred
		end

end
