-- This file has been generated by EWG. Do not edit. Changes will be lost!

deferred class QDPOLY_PROC_PTR_CALLBACK

feature {QDPOLY_PROC_PTR_DISPATCHER}

	on_callback (a_verb: INTEGER; a_poly: POINTER) is 
		deferred
		end

end
