-- This file has been generated by EWG. Do not edit. Changes will be lost!

deferred class QDPRINTER_STATUS_PROC_PTR_CALLBACK

feature {QDPRINTER_STATUS_PROC_PTR_DISPATCHER}

	on_callback (a_opcode: INTEGER; a_currentport: POINTER; a_printerstatus: POINTER): INTEGER is 
		deferred
		end

end
