-- This file has been generated by EWG. Do not edit. Changes will be lost!

deferred class QDPUT_PIC_PROC_PTR_CALLBACK

feature {QDPUT_PIC_PROC_PTR_DISPATCHER}

	on_callback (a_dataptr: POINTER; a_bytecount: INTEGER) is 
		deferred
		end

end
