-- This file has been generated by EWG. Do not edit. Changes will be lost!

deferred class QDSTD_GLYPHS_PROC_PTR_CALLBACK

feature {QDSTD_GLYPHS_PROC_PTR_DISPATCHER}

	on_callback (a_datastream: POINTER; a_size: INTEGER): INTEGER is 
		deferred
		end

end
