-- This file has been generated by EWG. Do not edit. Changes will be lost!

deferred class QDTX_MEAS_PROC_PTR_CALLBACK

feature {QDTX_MEAS_PROC_PTR_DISPATCHER}

	on_callback (a_bytecount: INTEGER; a_textaddr: POINTER; a_numer: POINTER; a_denom: POINTER; a_info: POINTER): INTEGER is 
		deferred
		end

end
