FROM daald/ubuntu32:xenial

LABEL maintainer="Jocelyn Fiat <jfiat@eiffel.com>"

RUN apt-get update && apt-get install -y --no-install-recommends --no-install-suggests \
        ca-certificates curl \
        bzip2 \
        gcc make dist \
        libxtst-dev \
        libgtk2.0-dev \
        libgtk-3-dev \
        libgdk-pixbuf2.0-dev \
        libssl-dev \
		pax \
		dos2unix \
		subversion \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*


#Define delivery variables
ENV USER_ID=1001 USER_GID=1001
ENV WORK_DIR=/opt/eiffel

# Define Eiffel environment variables
ENV ISE_PLATFORM=linux-x86
ENV PORTERPACKAGE_TAR=$WORK_DIR/deliv/output/PorterPackage.tar


RUN mkdir -p $WORK_DIR/deliv/image && mkdir $WORK_DIR/workspace 
COPY ./src/build.sh $WORK_DIR/build.sh
RUN dos2unix $WORK_DIR/build.sh


RUN apt update && apt install -y software-properties-common
RUN add-apt-repository ppa:gnome3-team/gnome3-staging
RUN add-apt-repository ppa:gnome3-team/gnome3
RUN apt update
RUN apt dist-upgrade -y

VOLUME $WORK_DIR/deliv/image

WORKDIR $WORK_DIR
CMD /bin/bash $WORK_DIR/build.sh $WORK_DIR/workspace $PORTERPACKAGE_TAR $WORK_DIR/deliv/image

