FROM ubuntu:20.04

LABEL maintainer="Jocelyn Fiat <jfiat@eiffel.com>"
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends --no-install-suggests \
        ca-certificates curl \
        bzip2 \
        gcc make dist \
        libxtst-dev \
        libgtk2.0-dev \
        libgtk-3-dev \
        libgdk-pixbuf2.0-dev \
        libssl-dev \
		pax \
		dos2unix \
		git \
		subversion \
		vim \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV WORK_DIR=/opt/eiffel

#Define delivery variables
ENV ISE_PLATFORM=linux-x86-64
ENV GIT_EIFFELSTUDIO_REPO=https://gitlab.com/eiffelsoftware/es.git
ENV SVN_ISE_REPO=svn://svn.ise/ise_svn
ENV EIFFEL_SETUP_CHANNEL=nightly
#ENV GIT_EIFFELSTUDIO_BRANCH=master

VOLUME $WORK_DIR/deliv/output
#VOLUME $WORK_DIR/Eiffel

RUN mkdir -p $WORK_DIR/deliv/output && mkdir $WORK_DIR/workspace
RUN ls -la -1R $WORK_DIR

WORKDIR $WORK_DIR

COPY ./src/build_porterpackage.sh $WORK_DIR/build_porterpackage.sh
RUN dos2unix $WORK_DIR/build_porterpackage.sh

WORKDIR $WORK_DIR
CMD /bin/bash $WORK_DIR/build_porterpackage.sh $WORK_DIR/deliv
