FROM ubuntu:20.04

LABEL maintainer="Jocelyn Fiat <jfiat@eiffel.com>"
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends --no-install-suggests \
        ca-certificates curl \
        bzip2 \
        gcc make dist \
        libxtst-dev \
        libgtk2.0-dev \
        libgtk-3-dev \
        libgdk-pixbuf2.0-dev \
        libssl-dev \
		pax \
		dos2unix \
		git \
		subversion \
		vim \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

#Define delivery variables
ENV ISE_PLATFORM=linux-x86-64
ENV GIT_EIFFELSTUDIO_REPO=https://gitlab.com/eiffelsoftware/es.git
ENV SVN_ISE_REPO=svn://svn.ise/ise_svn
ENV EIFFEL_SETUP_CHANNEL=nightly
#ENV GIT_EIFFELSTUDIO_BRANCH=master

VOLUME /home/eiffel/deliv/output
#VOLUME /home/eiffel/Eiffel

# now creating user
RUN groupadd  "eiffel" && \
    useradd \
      -m \
      --home-dir /home/eiffel \
      --shell /bin/bash \
      --gid eiffel \
      eiffel 
      # && \
      #chown -R eiffel:eiffel /home/eiffel #&& \
      #chmod a+w -R /home/eiffel/workspace

USER eiffel
WORKDIR /home/eiffel

RUN mkdir -p /home/eiffel/deliv/output && mkdir /home/eiffel/workspace && chown -R eiffel:eiffel /home/eiffel
COPY --chown=eiffel  ./src/build_porterpackage.sh /home/eiffel/build_porterpackage.sh
RUN dos2unix /home/eiffel/build_porterpackage.sh


WORKDIR /home/eiffel
CMD /bin/bash /home/eiffel/build_porterpackage.sh /home/eiffel/deliv
